language:
  - node_js
  - python

node_js:
  - "0.10"

services: redis-server

script: make travis
install: "pip install -r loadtests/requirements.txt"

notifications:
  irc:
    channels:
      - "irc.mozilla.org#loop"
    use_notice: false
    skip_join: true
    on_success: change
    on_failure: always
    template:
      - "%{repository} (%{branch} - %{commit}: %{author}): %{message} %{build_url}"
